dubbo:
  application:
    name: dubbo-springboot-demo-provider
  protocol:
    name: dubbo
    port: -1
    threads: 5000
    thread-pool: fixed
  registry:
    address: zookeeper://${zookeeper.address:127.0.0.1}:2181

spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
#  datasource:
#    url: jdbc:mysql://localhost:3306/myfirst?allowMultiQueries=true
#    username: root
#    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver
  datasource:
    url: jdbc:mysql://8.147.4.249:3306/myfirst
    username: root
    password: Administrator_
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8989