dubbo:
  application:
    name: dubbo-springboot-demo-web
  protocol:
    name: dubbo
    port: -1
    threads: 5000
    thread-pool: fixed
  registry:
    address: zookeeper://${zookeeper.address:127.0.0.1}:2181

spring:
  application:
    name: 菜粥天地银行
  jmx:
    enabled: false
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3306/myfirst?allowMultiQueries=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        enabled: true
    timeout: 60

#  datasource:
#    url: jdbc:mysql://8.147.4.249:3306/myfirst
#    username: root
#    password: Administrator_
#    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8988
  tomcat:
    threads:
      max: 5000
    accept-count: 5000
    max-connections: 8192
#  address: 0.0.0.0

mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml

machineId: 1
datacenterId: 1
#logging:
#  level:
#    com: debug
